### PR TITLE
fix: validate allocations locked amount in genesis to prevent panic

### LINKED ISSUE #3901: Invalid genesis bytes may panic
## Description

Avalanchego currently does not ensure that genesis creation gracefully errors. This bug was originally reported in #1173, but that PR did not necessarily ensure that all output genesis bytes are well-formed for the rest of initialization.

## Reproduction

See the original PR for an example genesis file that causes a panic.

## Suggested Fix

I originally had a comment to add additional validation to the geneisis parsing [here](https://github.com/ava-labs/avalanchego/pull/1173#issuecomment-1319381906).

### PR DESCRIPTION
**Pull request by DracoLi**
## Why this should be merged

Prevents panics when the allocations locked amount in genesis cannot be split across the initial stakers.
Fixes #3901

## How this works

Add `validateLockedAllocationsAmount` to genesis `validateConfig`

## How this was tested

Manually tested via `avalanchego --genesis-file=` and new unit test.

### CODE REVIEW

File: genesis/genesis.go [hunk 1]
```diff
@@ -533,7 +559,10 @@ func splitAllocations(allocations []Allocation, numSplits int) [][]Allocation {
 		}
 	}
 
-	return append(allNodeAllocations, currentNodeAllocation)
+	if len(currentNodeAllocation) > 0 {
+		allNodeAllocations = append(allNodeAllocations, currentNodeAllocation)
+	}
+	return allNodeAllocations
```
Comment (StephenButtolph) [inline genesis/genesis.go:565]: What does this modification do?

File: genesis/genesis_test.go [hunk 2]
```diff
@@ -118,6 +118,20 @@ func TestValidateConfig(t *testing.T) {
 			}(),
 			expectedErr: errInitialStakeDurationTooLow,
 		},
+		"locked allocations amount too low": {
```
Comment (joshua-kim) [inline genesis/genesis_test.go:121]: This technically works... I'm not a fan of this existing test though because it tests through `validateConfig` which isn't a part of this package's exported API though. I think a majority of these tests are actually invalid configs, because they would all fail the network id check. Can we test this through the calling code which is `FromFile`? We have an existing test `TestGenesisFromFile` which is set up to do this... we could also use the user-provided genesis config that revealed this bug linked on https://github.com/ava-labs/avalanchego/pull/1173

File: genesis/genesis.go (hunk 1 above)
Comment (DracoLi) [reply genesis/genesis.go:565]: not required for the fix and can be omitted. 
this modification ensures we don't return an array with an empty nested array when no locked amount. https://github.com/ava-labs/avalanchego/pull/3941/files/2842951c8860726232091bff268849ce0ff7117e#diff-2ce354664b078c8815c9e3644165471d1b47b509a4ce00763895428f2f1f384bR514-R515

File: genesis/genesis_test.go (hunk 2 above)
Comment (DracoLi) [reply genesis/genesis_test.go:121]: sounds good, i'll move this test to be part of FromFile.

File: genesis/genesis_test.go [hunk 3]
```diff
@@ -118,15 +121,6 @@ func TestValidateConfig(t *testing.T) {
...
 		},
-		"empty initial staked funds": {
-			networkID: 12345,
-			config: func() *Config {
-				thisConfig := LocalConfig
-				thisConfig.InitialStakedFunds = []ids.ShortID(nil)
-				return &thisConfig
-			}(),
-			expectedErr: errNoInitiallyStakedFunds,
-		},
```
Comment (joshua-kim) [inline genesis/genesis_test.go:129]: Did we mean to remove this? I think this is a different case than the insufficient allocations case

Comment (DracoLi) [reply genesis/genesis_test.go:129]: definitely not, i'll need to add this back

**Review by StephenButtolph — APPROVED** [review]

**Review by joshua-kim — APPROVED** [review]
