### PR TITLE
test: Use predictable accounts for TestTracingwithOverrides

### LINKED ISSUE #4560: Fix `TestTracingWithOverrides` flake
There's a weird flake in the eth/tracer tests that seems to have appeared once the test was introduced: https://github.com/ava-labs/coreth/actions/runs/18568007433/job/52934285055
It happens on ubuntu with race detection about 0.5% of the time for me.

The ultimate source is that [this](https://github.com/ava-labs/libevm/blob/1bccf4f2ddb28ff440f9e24f46506a2e98ad2a0d/core/vm/errors.go#L38) error is being returned on the final tracer test:
```go
       { // Override blocknumber with block n+1 and query a blockhash (resolves issue #32175)
			blockNumber: rpc.LatestBlockNumber,
			call: ethapi.TransactionArgs{
				From: &accounts[0].addr,
				Input: newRPCBytes([]byte{
					byte(vm.PUSH1), byte(genBlocks),
					byte(vm.BLOCKHASH),
					byte(vm.PUSH1), 0x00,
					byte(vm.MSTORE),
					byte(vm.PUSH1), 0x20,
					byte(vm.PUSH1), 0x00,
					byte(vm.RETURN),
				}),
			},
			config: &TraceCallConfig{
				BlockOverrides: &ethapi.BlockOverrides{Number: (*hexutil.Big)(big.NewInt(int64(genBlocks + 1)))},
			},
			want: fmt.Sprintf(`{"gas":59592,"failed":false,"returnValue":"%x"}`, backend.chain.GetHeaderByNumber(uint64(genBlocks)).Hash()),
		}
```

This test was added in ava-labs/coreth#1301 and can be replicated with HashDB. I'm not sure what part of this behavior is non-deterministic.

### PR DESCRIPTION
**Pull request by alarso16**
## Why this should be merged

This test flakes because every once in a while, the final block hash starts with `0xef`, which is incompatible with the London hard fork. It's unintuitive that the `ErrInvalidCode` error would be encountered for return values that are not code hashes, but this testing only fix will remove failures in CI

Closes #4560

## How this works

Uses a random seed to pre-fill the state with the same data every time.

## How this was tested

Locally, logging the resulting block hash.

## Need to be documented in RELEASES.md?

No

### CODE REVIEW

**Review by JonathanOppenheimer — APPROVED** [review]

File: graft/coreth/eth/tracers/api_test.go [hunk 1]
```diff
@@ -996,6 +999,18 @@ func newAccounts(n int) (accounts []Account) {
 	return accounts
 }
 
+// WARNING: only use for tests that require deterministic accounts
+func newAccountsWithSeed(n int, seed int64) (accounts []Account) {
+	rand := rand.New(rand.NewSource(seed))
+	for i := 0; i < n; i++ {
+		key, _ := ecdsa.GenerateKey(crypto.S256(), rand)
```
[the remark this answers is not in the document]
Comment (alarso16) [reply graft/coreth/eth/tracers/api_test.go]: I don't plan on addressing this. If others agree with Copilot on this one, then I'll change it

File: graft/coreth/eth/tracers/api_test.go [hunk 2]
```diff
@@ -996,6 +999,18 @@ func newAccounts(n int) (accounts []Account) {
 	return accounts
 }
 
+// WARNING: only use for tests that require deterministic accounts
+func newAccountsWithSeed(n int, seed int64) (accounts []Account) {
+	rng := rand.New(rand.NewSource(seed))
+	for i := 0; i < n; i++ {
+		key, _ := ecdsa.GenerateKey(crypto.S256(), rng)
```
Comment (ARR4N) [inline graft/coreth/eth/tracers/api_test.go]: This is documented as not being deterministic, even with the same seed. Use `libevm/ethtest.UNSAFEDeterministicPrivateKey()` instead.

Comment (alarso16) [reply graft/coreth/eth/tracers/api_test.go]: Weird! Can we tag a new libevm release so we can use it?

**Comment by alarso16** [comment]
I'm not changing the dependencies right before subnet-evm merger, so I'll just wait to push for a review

File: graft/coreth/eth/tracers/api_test.go [hunk 3]
```diff
@@ -996,6 +1000,19 @@ func newAccounts(n int) (accounts []Account) {
 	return accounts
 }
 
+// WARNING: only use for tests that require deterministic accounts
+func UNSAFEDeterministicAccounts(t *testing.T, n int) (accounts []Account) {
+	seed := make([]byte, 8) // int64 size
+	for i := 0; i < n; i++ {
+		binary.BigEndian.PutUint64(seed, uint64(i))
```
Comment (ARR4N) [inline graft/coreth/eth/tracers/api_test.go]:
```suggestion
func UNSAFEDeterministicAccounts(t *testing.T, n uint64) (accounts []Account) {
	seed := make([]byte, 8) // int64 size
	for i := range n {
		binary.BigEndian.PutUint64(seed, i)
```

File: graft/coreth/eth/tracers/api_test.go [hunk 4]
```diff
@@ -996,6 +1000,19 @@ func newAccounts(n int) (accounts []Account) {
...
+		key := ethtest.UNSAFEDeterministicPrivateKey(t, seed)
+		addr := crypto.PubkeyToAddress(key.PublicKey)
+		accounts = append(accounts, Account{key: key, addr: addr})
+	}
+	slices.SortFunc(accounts, func(a, b Account) int { return a.addr.Cmp(b.addr) })
```
Comment (ARR4N) [inline graft/coreth/eth/tracers/api_test.go]: Why sort them?

File: graft/subnet-evm/eth/tracers/api_test.go [hunk 5]
```diff
@@ -628,7 +630,9 @@ func TestTracingWithOverrides(t *testing.T) {
 
 func testTracingWithOverrides(t *testing.T, scheme string) {
 	// Initialize test accounts
-	accounts := newAccounts(3)
+	// This test requires deterministic block hashes, since it will fail 1/256 times,Expand commentComment on line R635ResolvedCode has comments. Press enter to view.
```
Comment (ARR4N) [inline graft/subnet-evm/eth/tracers/api_test.go]: > Expand commentComment on line R635ResolvedCode

?

File: graft/subnet-evm/eth/tracers/api_test.go [hunk 6]
```diff
@@ -994,6 +998,19 @@ func newAccounts(n int) (accounts []Account) {
 	return accounts
 }
 
+// WARNING: only use for tests that require deterministic accounts
+func UNSAFEDeterministicAccounts(t *testing.T, n int) (accounts []Account) {
+	seed := make([]byte, 8) // int64 size
+	for i := 0; i < n; i++ {
+		binary.BigEndian.PutUint64(seed, uint64(i))
```
Comment (ARR4N) [inline graft/subnet-evm/eth/tracers/api_test.go]:
```suggestion
func UNSAFEDeterministicAccounts(t *testing.T, n uint64) (accounts []Account) {
	seed := make([]byte, 8) // int64 size
	for i := range n {
		binary.BigEndian.PutUint64(seed, i)
```

File: graft/subnet-evm/eth/tracers/api_test.go (hunk 5 above)
Comment (alarso16) [reply graft/subnet-evm/eth/tracers/api_test.go]: Whoa, that's weird...

**Review by StephenButtolph — APPROVED** [review]
