### PR TITLE
Fix unreadable message errors

### LINKED ISSUE #1540: Unreadable error message being produced by the engine handler
We currently use `%s` to format messages when processing FATAL errors. However, `msg` never implements `strings.Stringer`.

- https://github.com/ava-labs/avalanchego/blob/ef6a2a2f7facd8fbefd5fb2ac9c4908c2bcae3e2/snow/networking/handler/handler.go#L360-L364
- https://github.com/ava-labs/avalanchego/blob/ef6a2a2f7facd8fbefd5fb2ac9c4908c2bcae3e2/snow/networking/handler/handler.go#L414-L418
  - The wording here is also incorrect, it should be `chan` not `async` here.
- https://github.com/ava-labs/avalanchego/blob/ef6a2a2f7facd8fbefd5fb2ac9c4908c2bcae3e2/snow/networking/handler/handler.go#L742-L746

### PR DESCRIPTION
**Pull request by morrisettjohn**
## Why this should be merged

Resolves #1540

### CODE REVIEW

File: snow/networking/handler/handler.go [hunk 1]
```diff
@@ -740,9 +740,9 @@ func (h *handler) handleAsyncMsg(ctx context.Context, msg Message) {
 	h.asyncMessagePool.Send(func() {
 		if err := h.executeAsyncMsg(ctx, msg); err != nil {
 			h.StopWithError(ctx, fmt.Errorf(
-				"%w while processing async message: %s",
+				"%w while processing chan message: %s",
```
Comment (StephenButtolph) [inline snow/networking/handler/handler.go:743]: I think this was correct before:
```suggestion
				"%w while processing async message: %s",
```

File: snow/networking/handler/handler.go [hunk 2]
```diff
@@ -414,7 +414,7 @@ func (h *handler) dispatchChans(ctx context.Context) {
 			h.StopWithError(ctx, fmt.Errorf(
 				"%w while processing async message: %s",
```
Comment (StephenButtolph) [inline snow/networking/handler/handler.go:415]: This was the log that needed to be changed
```suggestion
				"%w while processing chan message: %s",
```

File: snow/networking/handler/handler.go [hunk 3]
```diff
@@ -360,7 +360,7 @@ func (h *handler) dispatchSync(ctx context.Context) {
 			h.StopWithError(ctx, fmt.Errorf(
 				"%w while processing sync message: %s",
 				err,
-				msg,
+				msg.Op().String(),
```
Comment (StephenButtolph) [inline snow/networking/handler/handler.go:363]: Because these are serious errors - I do think we want to have the error include the full message (not just the message type).

We should think about embedding the `fmt.Stringer` interface to the `message.InboundMessage` interface.

File: snow/networking/handler/handler.go (hunk 2 above)
Comment (morrisettjohn) [reply snow/networking/handler/handler.go:415]: Ok cool, I can switch that up

File: snow/networking/handler/handler.go (hunk 3 above)
Comment (morrisettjohn) [reply snow/networking/handler/handler.go:363]: The biggest problem currently is that Inbound message's message field can be returned as any.  Specifically, it returns  messages defined by protobuf in proto/p2p/p2p.pb.go, none of which implement stringer.  I'll take a look at protobuf and see if there's a way to regenerate the messages such that they all can implement stringer.

Comment (StephenButtolph) [reply snow/networking/handler/handler.go:363]: All of the proto messages implement stringer. ex: https://github.com/ava-labs/avalanchego/blob/master/proto/pb/p2p/p2p.pb.go#L516

File: snow/networking/handler/message_queue.go [hunk 4]
```diff
@@ -32,6 +32,10 @@ type Message struct {
 	EngineType p2p.EngineType
 }
 
+func (m Message) String() string {
+	return m.Message().String()
+}
+
```
Comment (StephenButtolph) [inline snow/networking/handler/message_queue.go:38]: Because `message.InboundMessage` specifies a `String() string` function, I don't think we need to implement this here (it will be inherited).

File: snow/networking/handler/handler.go [hunk 5]
```diff
@@ -742,7 +742,7 @@ func (h *handler) handleAsyncMsg(ctx context.Context, msg Message) {
 			h.StopWithError(ctx, fmt.Errorf(
 				"%w while processing async message: %s",
 				err,
-				msg,
+				msg.String(),
```
Comment (StephenButtolph) [inline snow/networking/handler/handler.go:745]: I don't think we actually need to call `.String()` here, `fmt.Errorf` should do it for us. (Same above)

File: message/messages.go [hunk 6]
```diff
@@ -86,6 +88,10 @@ func (m *inboundMessage) BytesSavedCompression() int {
 	return m.bytesSavedCompression
 }
 
+func (m *inboundMessage) String() string {
+	return m.Message().String()
```
Comment (StephenButtolph) [inline message/messages.go:92]: I think we probably want to include the `nodeID` + `op` + `m.message` in the output here.

File: message/messages.go [hunk 7]
```diff
@@ -49,12 +49,14 @@ type InboundMessage interface {
 	// BytesSavedCompression returns the number of bytes that this message saved
 	// due to being compressed
 	BytesSavedCompression() int
+	// Returns string representation of message
+	String() string
```
Comment (StephenButtolph) [inline message/messages.go:53]: We should embed `fmt.Stringer` at the top of this interface rather than re-specifying the method signature.

File: message/internal_msg_builder.go [hunk 8]
```diff
@@ -491,6 +566,12 @@ type VMMessage struct {
 	Notification uint32 `json:"notification,omitempty"`
 }
 
+func (m *VMMessage) String() string {
+	return fmt.Sprintf(
+		"Notification: %v",
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:571]: `%v` is kinda the catch all - I like to be explicit:
```suggestion
		"Notification: %d",
```

File: message/internal_msg_builder.go [hunk 9]
```diff
@@ -463,6 +528,12 @@ type ConnectedSubnet struct {
 	SubnetID ids.ID `json:"subnet_id,omitempty"`
 }
 
+func (m *ConnectedSubnet) String() string {
+	return fmt.Sprintf(
+		"SubnetID: %v",
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:533]:
```suggestion
		"SubnetID: %s",
```

File: message/internal_msg_builder.go [hunk 10]
```diff
@@ -446,6 +505,12 @@ type Connected struct {
 	NodeVersion *version.Application `json:"node_version,omitempty"`
 }
 
+func (m *Connected) String() string {
+	return fmt.Sprintf(
+		"NodeVersion: %v",
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:510]:
```suggestion
		"NodeVersion: %s",
```

File: message/internal_msg_builder.go [hunk 11]
```diff
@@ -410,6 +463,12 @@ type CrossChainAppResponse struct {
 	Message            []byte `json:"message,omitempty"`
 }
 
+func (m *CrossChainAppResponse) String() string {
+	return fmt.Sprintf(
+		"SourceChainID: %v DestinationChainID: %v EngineType: %v Message: %v",
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:468]:
```suggestion
		"SourceChainID: %s DestinationChainID: %s RequestID: %d Message: 0x%x",
```

File: message/messages.go [hunk 12]
```diff
@@ -49,12 +50,14 @@ type InboundMessage interface {
...
```
Comment (StephenButtolph) [inline message/messages.go:54]: We can delete this

File: snow/networking/handler/message_queue.go (hunk 4 above)
Comment (StephenButtolph) [inline snow/networking/handler/message_queue.go:38]: We can delete this

File: message/internal_msg_builder.go [hunk 13]
```diff
@@ -520,6 +605,10 @@ func InternalGossipRequest(
 
 type Timeout struct{}
 
+func (_ Timeout) String() string {
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:608]: super nit, but typically we do:
```suggestion
func (Timeout) String() string {
```
rather than using the `_`

File: message/internal_msg_builder.go [hunk 14]
```diff
@@ -373,6 +420,12 @@ type CrossChainAppRequestFailed struct {
 	RequestID          uint32 `json:"request_id,omitempty"`
 }
 
+func (m *CrossChainAppRequestFailed) String() string {
+	return fmt.Sprintf(
+		"SourceChainID: %s DestinationChainID: %s EngineType: %d",
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:425]:
```suggestion
		"SourceChainID: %s DestinationChainID: %s RequestID: %d",
```

File: message/internal_msg_builder.go [hunk 15]
```diff
@@ -334,6 +375,12 @@ type CrossChainAppRequest struct {
 	Message            []byte `json:"message,omitempty"`
 }
 
+func (m *CrossChainAppRequest) String() string {
+	return fmt.Sprintf(
+		"SourceChainID: %s DestinationChainID: %s EngineType: %d Message: %s",
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:380]:
```suggestion
		"SourceChainID: %s DestinationChainID: %s RequestID: %d Message: 0x%x",
```

File: message/internal_msg_builder.go [hunk 16]
```diff
@@ -507,6 +588,10 @@ func InternalVMMessage(
 
 type GossipRequest struct{}
 
+func (_ GossipRequest) String() string {
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:591]:
```suggestion
func (GossipRequest) String() string {
```

File: message/internal_msg_builder.go [hunk 17]
```diff
@@ -478,6 +549,10 @@ func InternalConnectedSubnet(nodeID ids.NodeID, subnetID ids.ID) InboundMessage
 
 type Disconnected struct{}
 
+func (_ Disconnected) String() string {
```
Comment (StephenButtolph) [inline message/internal_msg_builder.go:552]:
```suggestion
func (Disconnected) String() string {
```

**Review by StephenButtolph — APPROVED** [review]

**Review by darioush — APPROVED** [review]

File: message/internal_msg_builder.go [hunk 18]
```diff
@@ -478,6 +587,10 @@ func InternalConnectedSubnet(nodeID ids.NodeID, subnetID ids.ID) InboundMessage
 
 type Disconnected struct{}
 
+func (Disconnected) String() string {
+	return ""
```
Comment (ceyonur) [inline message/internal_msg_builder.go:591]: Just a late question: Why some of these are empty?
