### PR TITLE
fix: blockdb file eviction race issue

### LINKED ISSUE #4194: Flaky Test: BlockDB TestFileCache_Eviction
https://github.com/ava-labs/avalanchego/actions/runs/17131191843/job/48595661223#step:4:601

Image

### PR DESCRIPTION
**Pull request by DracoLi**
## Why this should be merged

Fix race for when a data file handler is evicted but another thread is still using that handler. The eviction tests caught this issue. See [example](https://github.com/ava-labs/avalanchego/actions/runs/17076901774/job/48420613984?pr=4184), [example 2](https://github.com/ava-labs/avalanchego/actions/runs/17080605904/job/48433319015?pr=4159)

Resolves #4194

## How this works

The eviction tests caught this since it simulated high evictions during concurrent calls. The simple solution here is to just retry opening the data file if we get an `os.ErrClosed` error during data file read/write, which should be rare.

## How this was tested

Tests

### CODE REVIEW

File: x/blockdb/database.go [hunk 1]
```diff
@@ -1134,16 +1149,37 @@ func (s *Database) writeBlockAt(offset uint64, bh blockEntryHeader, block BlockD
...
+		if !dataWritten {
+			if _, err := dataFile.WriteAt(combinedBuf, int64(localOffset)); err != nil {
+				if errors.Is(err, os.ErrClosed) {
+					// ensure the file is evicted, otherwise we'll retry forever
+					s.fileCache.Evict(fileIndex)
+					continue
+				}
+				return fmt.Errorf("failed to write block to data file at offset %d: %w", offset, err)
+			}
+			dataWritten = true
```
[the remark this answers is not in the document]
Comment (DracoLi) [reply x/blockdb/database.go]: this is for the sync call later, to avoid the write

File: x/blockdb/database.go [hunk 2]
```diff
@@ -1134,16 +1149,37 @@ func (s *Database) writeBlockAt(offset uint64, bh blockEntryHeader, block BlockD
 	combinedBuf := make([]byte, combinedBufSize)
 	copy(combinedBuf, headerBytes)
 	copy(combinedBuf[sizeOfBlockEntryHeader:], block)
-	if _, err := dataFile.WriteAt(combinedBuf, int64(localOffset)); err != nil {
-		return fmt.Errorf("failed to write block to data file at offset %d: %w", offset, err)
-	}
+	dataWritten := false
```
[the remark this answers is not in the document]
Comment (DracoLi) [reply x/blockdb/database.go]: no need to rewrite the data if its already written. I think better to keep.

File: x/blockdb/database.go [hunk 3]
```diff
@@ -567,44 +580,51 @@ func (s *Database) ReadBody(height BlockHeight) (BlockData, error) {
...
-	if err != nil {
-		s.log.Error("Failed to read body: body offset calculation overflow",
-			zap.Uint64("height", height),
-			zap.Uint64("headerOffset", headerOffset),
-			zap.Uint32("headerSize", indexEntry.HeaderSize),
-			zap.Error(err),
-		)
-		return nil, fmt.Errorf("calculating body offset would overflow for block at height %d: %w", height, err)
-	}
+	for {
```
Comment (DracoLi) [inline x/blockdb/database.go:588]: the read body and header methods will be moved soon.

File: x/blockdb/database.go [hunk 4]
```diff
@@ -480,26 +480,32 @@ func (s *Database) ReadBlock(height BlockHeight) (BlockData, error) {
...
-	_, err = dataFile.ReadAt(blockData, int64(localOffset+uint64(sizeOfBlockEntryHeader)))
-	if err != nil {
-		s.log.Error("Failed to read block: failed to read block data from file",
-			zap.Uint64("height", height),
-			zap.Uint64("localOffset", localOffset),
-			zap.Uint32("blockSize", indexEntry.Size),
-			zap.Error(err),
-		)
-		return nil, fmt.Errorf("failed to read block data from data file: %w", err)
+	for {
```
Comment (StephenButtolph) [inline x/blockdb/database.go:486]: We should probably add a comment as to why this loop is needed.

File: x/blockdb/database_test.go [hunk 5]
```diff
@@ -235,7 +235,7 @@ func TestFileCache_Eviction(t *testing.T) {
 	// Override the file cache with a smaller size to force evictions
 	evictionCount := atomic.Int32{}
 	evictionMu := sync.Mutex{}
-	smallCache := lru.NewCacheWithOnEvict[int, *os.File](3, func(_ int, file *os.File) {
+	smallCache := lru.NewCacheWithOnEvict(3, func(_ int, file *os.File) {
```
Comment (yacovm) [inline x/blockdb/database_test.go]: Is it possible to make a test that fails without the fix with a high probability?

File: x/blockdb/database.go [hunk 6]
```diff
@@ -531,24 +537,31 @@ func (s *Database) ReadHeader(height BlockHeight) (BlockData, error) {
...
+			}
+			s.log.Error("Failed to read header: failed to read header data from file",
+				zap.Uint64("height", height),
+				zap.Uint64("localOffset", localOffset),
+				zap.Uint32("headerSize", indexEntry.HeaderSize),
+				zap.Error(err),
+			)
+			return nil, fmt.Errorf("failed to read block header data from data file: %w", err)
+		}
+		break
```
Comment (yacovm) [inline x/blockdb/database.go]: can we explicitly use `return` here instead?

File: x/blockdb/database.go [hunk 7]
```diff
@@ -567,44 +580,51 @@ func (s *Database) ReadBody(height BlockHeight) (BlockData, error) {
...
+			}
+			s.log.Error("Failed to read body: failed to read body data from file",
+				zap.Uint64("height", height),
+				zap.Uint64("bodyOffset", bodyOffset),
+				zap.Uint32("bodySize", bodySize),
+				zap.Error(err),
+			)
+			return nil, fmt.Errorf("failed to read block body data from data file: %w", err)
+		}
+		break
```
Comment (yacovm) [inline x/blockdb/database.go]: can we explicitly use `return` here?

File: x/blockdb/database.go [hunk 8]
```diff
@@ -1134,14 +1149,36 @@ func (s *Database) writeBlockAt(offset uint64, bh blockEntryHeader, block BlockD
...
+		if s.config.SyncToDisk {
+			if err := dataFile.Sync(); err != nil {
+				if errors.Is(err, os.ErrClosed) {
+					s.fileCache.Evict(fileIndex)
+					continue
+				}
+				return fmt.Errorf("failed to sync data file after writing block %d: %w", bh.Height, err)
+			}
 		}
+		break
```
Comment (yacovm) [inline x/blockdb/database.go]: same, can we use `return` here?

File: x/blockdb/database.go [hunk 9]
```diff
@@ -1134,14 +1149,36 @@ func (s *Database) writeBlockAt(offset uint64, bh blockEntryHeader, block BlockD
...
-	if s.config.SyncToDisk {
-		if err := dataFile.Sync(); err != nil {
-			return fmt.Errorf("failed to sync data file after writing block %d: %w", bh.Height, err)
+	for {
+		dataFile, localOffset, fileIndex, err := s.getDataFileAndOffset(offset)
+		if err != nil {
+			return fmt.Errorf("failed to get data file for writing block %d: %w", bh.Height, err)
+		}
+
+		if !dataWritten {
```
Comment (yacovm) [inline x/blockdb/database.go]: why do we skip overwriting? 

If we have pending bytes to be written to the file but we closed the file, are we guaranteed that if we re-open the file and call sync, the changes from before will be written? 

Isn't that dependent on the implementation of the file handle? The file handle in the next iteration isn't the same as the one in the previous one.

Can't we just overwrite the changes again? we're not appending to the file but writing to a specific offset, right?  Then the code will also be simpler.

Comment (DracoLi) [reply x/blockdb/database.go]: yeah good point, I'm convinced. I think its fine to just rewrite the data in this case if sync fails.

**Review by yacovm — APPROVED** [review]

File: x/blockdb/database_test.go (hunk 5 above)
Comment (DracoLi) [reply x/blockdb/database_test.go]: yep, i added a test that trigger this 100%

File: x/blockdb/database.go [hunk 10]
```diff
@@ -221,7 +221,7 @@ func New(config DatabaseConfig, log logging.Logger) (*Database, error) {
 	s := &Database{
 		config: config,
 		log:    databaseLog,
-		fileCache: lru.NewCacheWithOnEvict[int, *os.File](config.MaxDataFiles, func(_ int, f *os.File) {
```
Comment (joshua-kim) [inline x/blockdb/database.go]: nit: remove unrelated diff

File: x/blockdb/database.go [hunk 11]
```diff
@@ -480,26 +480,35 @@ func (s *Database) ReadBlock(height BlockHeight) (BlockData, error) {
...
+			}
+			s.log.Error("Failed to read block: failed to read block data from file",
+				zap.Uint64("height", height),
+				zap.Uint64("localOffset", localOffset),
+				zap.Uint32("blockSize", indexEntry.Size),
+				zap.Error(err),
+			)
+			return nil, fmt.Errorf("failed to read block data from data file: %w", err)
+		}
+		break
```
Comment (joshua-kim) [inline x/blockdb/database.go]: Should we just move the `return` to here?

File: x/blockdb/database.go [hunk 12]
```diff
@@ -480,26 +480,35 @@ func (s *Database) ReadBlock(height BlockHeight) (BlockData, error) {
...
+				zap.Uint64("height", height),
+				zap.Uint64("dataOffset", indexEntry.Offset),
+				zap.Error(err),
+			)
+			return nil, fmt.Errorf("failed to get data file for block at height %d: %w", height, err)
+		}
+		_, err = dataFile.ReadAt(blockData, int64(localOffset+uint64(sizeOfBlockEntryHeader)))
+		if err != nil {
+			if errors.Is(err, os.ErrClosed) {
+				s.fileCache.Evict(fileIndex)
```
Comment (joshua-kim) [inline x/blockdb/database.go:499]: I don't understand why we need to call evict here - evicting will close the file handle but doesn't this error mean it's already closed?

File: x/blockdb/database.go [hunk 13]
```diff
@@ -1134,16 +1154,35 @@ func (s *Database) writeBlockAt(offset uint64, bh blockEntryHeader, block BlockD
...
+	for {
+		dataFile, localOffset, fileIndex, err := s.getDataFileAndOffset(offset)
+		if err != nil {
+			return fmt.Errorf("failed to get data file for writing block %d: %w", bh.Height, err)
+		}
+
+		if _, err := dataFile.WriteAt(combinedBuf, int64(localOffset)); err != nil {
+			if errors.Is(err, os.ErrClosed) {
+				// ensure the file is evicted, otherwise we'll retry forever
+				s.fileCache.Evict(fileIndex)
```
Comment (joshua-kim) [inline x/blockdb/database.go:1168]: Ah nvm the reason is documented here.

File: x/blockdb/database.go (hunk 11 above)
Comment (DracoLi) [reply x/blockdb/database.go]: yeah, i missed updating this one
