### PR TITLE
test: address geth flakes

### LINKED ISSUE #4557: Fix `TestBlockChainOfflinePruningUngracefulShutdown` flakes
I've never seen [this](https://github.com/ava-labs/coreth/actions/runs/18782331359/job/53591490076?pr=1361) flake before. I'm not sure what caused this.

### LINKED ISSUE #4558: Epic: fix flaky EVM tests
Flaky tests must be fixed to enable mono-repo goals of the EVM team. As the rerunning infrastructure has been deleted, these flaky tests will cause instant, annoying, CI fails.

### LINKED ISSUE #4702: Fix `TestStateSyncToggleEnabledToDisabled` flake
See https://github.com/ava-labs/subnet-evm/actions/runs/19942508463/job/57183692605?pr=1896

### LINKED ISSUE #4751: Fix `TestTxLookupBlockChain` flake
See https://github.com/ava-labs/avalanchego/actions/runs/20281071849/job/58242872336?pr=4749

### LINKED ISSUE #4807: Fix `TestClientCancelWebsocket` flake
See https://github.com/ava-labs/avalanchego/actions/runs/20723963169/job/59494825567?pr=4786

### LINKED ISSUE #4907: Fix `TestClientWebsocketLargeMessage`
See https://github.com/ava-labs/avalanchego/actions/runs/21297670076/job/61307307307?pr=4865

### PR DESCRIPTION
**Pull request by JonathanOppenheimer**
## Why this should be merged

There are a number of existing flakes within the grafted repository. Some of these are due to insufficient execution time, and some are just actual flakes. This PR parallelizes subtests across both `graft/coreth/core` and `graft/subnet-evm/core`, while skipping actually flaky tests. 

- Closes #4558 - hopefully we don't have to re-open this! 
  - Closes #4557 - actually flaky 
  - Closes #4702 - actually flaky 
  - Closes #4907 - actually flaky
  - Closes #4751 - times out 
  - Closes #4807 - times out 

## How this works

- Skipped flaky tests with `t.Skip`
- Added `t.Parallel()` calls to subtests in the main blockchain test suites:
  - All blockchain configuration test variants (archive, pruning, snapshot-disabled, etc.) now run their subtests in parallel
  - Multiple scheme tests (HashScheme, PathScheme, FirewoodScheme) now run concurrently

## How this was tested

No test logic modified - CI 

## Need to be documented in RELEASES.md?

No

### CODE REVIEW

File: graft/coreth/core/blockchain_test.go [hunk 1]
```diff
@@ -370,12 +382,14 @@ func TestCorruptSnapshots(t *testing.T) {
...
 	for _, tt := range tests {
 		t.Run(tt.Name, func(t *testing.T) {
+			t.Parallel()
 			tt.testFunc(t, create)
 		})
 	}
 }
 
 func TestBlockChainOfflinePruningUngracefulShutdown(t *testing.T) {
+	t.Skip("Flaky test from go-ethereum")
```
Comment (alarso16) [inline graft/coreth/core/blockchain_test.go:379]: I do not believe this is flaky

File: graft/coreth/rpc/websocket_test.go [hunk 2]
```diff
@@ -184,6 +184,8 @@ func TestWebsocketLargeRead(t *testing.T) {
 }
 
 func TestWebsocketPeerInfo(t *testing.T) {
```
Comment (alarso16) [inline graft/coreth/rpc/websocket_test.go:186]: I'm not sure this is a helpful optimization

File: graft/evm/scripts/build_test.sh [hunk 3]
```diff
@@ -16,4 +16,4 @@ fi
 
 cd "$REPO_ROOT/graft/evm"
 # shellcheck disable=SC2046
-go test -shuffle=on ${race:-} -timeout="${TIMEOUT:-600s}" -coverprofile=coverage.out -covermode=atomic "$@" ./...
+go test -shuffle=on ${race:-} -timeout="${TIMEOUT:-900s}" -coverprofile=coverage.out -covermode=atomic "$@" ./...
```
Comment (alarso16) [inline graft/evm/scripts/build_test.sh]: Do we actually need to increase this for this package?

File: graft/subnet-evm/plugin/evm/syncervm_test.go [hunk 4]
```diff
@@ -86,6 +86,8 @@ func TestStateSyncFromScratchExceedParent(t *testing.T) {
 }
 
 func TestStateSyncToggleEnabledToDisabled(t *testing.T) {
+	t.Skip("@TODO(JonathanOppenheimer):flaky test -- this *must* get fixed in the sync refactor @powerslider")
```
Comment (alarso16) [inline graft/subnet-evm/plugin/evm/syncervm_test.go]: I don't think this is the canonical way to reference the issue
```suggestion
	// TODO(#issue-number): should be fixed with state sync refactor
	t.Skip("Flaky test")
```

File: graft/subnet-evm/rpc/websocket_test.go [hunk 5]
```diff
@@ -281,7 +283,7 @@ func TestClientWebsocketPing(t *testing.T) {
 // This test is upstream from go-ethereum but is skipped because it is flaky.
 // Error message: call failed: websocket: close 1006 (abnormal closure): unexpected EOF
 func TestClientWebsocketLargeMessage(t *testing.T) {
-	t.Skip("Flaky")
+	t.Skip("Flaky test from go-ethereum")
```
Comment (alarso16) [inline graft/subnet-evm/rpc/websocket_test.go:272]: You skip this here, but run in parallel above. I believe this test is actually flaky and should be skipped for both

File: graft/coreth/core/blockchain_test.go [hunk 6]
```diff
@@ -113,6 +114,7 @@ func TestArchiveBlockChain(t *testing.T) {
 func TestArchiveBlockChainSnapsDisabled(t *testing.T) {
 	for _, scheme := range schemes {
 		t.Run(scheme, func(t *testing.T) {
+			t.Parallel()
```
Comment (alarso16) [inline graft/coreth/core/blockchain_test.go]: This `t.Parallel()` doesn't really do anything

File: graft/coreth/core/blockchain_test.go [hunk 7]
```diff
@@ -162,6 +166,7 @@ func TestPruningBlockChain(t *testing.T) {
 func TestPruningBlockChainSnapsDisabled(t *testing.T) {
 	for _, scheme := range schemes {
 		t.Run(scheme, func(t *testing.T) {
+			t.Parallel()
```
Comment (alarso16) [inline graft/coreth/core/blockchain_test.go]: This one too

File: graft/coreth/core/blockchain_test.go [hunk 8]
```diff
@@ -200,6 +206,7 @@ func testPruningBlockChainSnapsDisabled(t *testing.T, scheme string) {
 func TestPruningEmptyCallbacks(t *testing.T) {
 	for _, scheme := range schemes {
 		t.Run(scheme, func(t *testing.T) {
+			t.Parallel()
```
Comment (alarso16) [inline graft/coreth/core/blockchain_test.go]: This one as well. Trace the function calls, but you should hope for one `t.Parallel` per sub-test

**Review by alarso16 — DISMISSED** [review]
If we are choosing to run the `core` tests in parallel, some of the repair tests are also very slow and likely would benefit form running in parallel.

Also, did you confirm that running the tests in parallel is actually faster? Sometimes with race detection, running in parallel will be not-significant or even slower...

File: graft/subnet-evm/core/blockchain_test.go [hunk 9]
```diff
@@ -299,6 +308,7 @@ func TestEnableSnapshots(t *testing.T) {
 	}
 	for _, tt := range tests {
 		t.Run(tt.Name, func(t *testing.T) {
+			t.Parallel()
```
Comment (alarso16) [inline graft/subnet-evm/core/blockchain_test.go]: This one can't be run in parallel (look at the boolean in `create`). You should either not run this in parallel or fix the test setup

File: graft/evm/scripts/build_test.sh (hunk 3 above)
Comment (JonathanOppenheimer) [reply graft/evm/scripts/build_test.sh]: We might as well keep them all consistent, especially as consolidation continues and more of the test workload gets moved to this package.

File: graft/coreth/core/blockchain_test.go (hunk 1 above)
Comment (JonathanOppenheimer) [reply graft/coreth/core/blockchain_test.go:379]: Take a look at https://github.com/ava-labs/avalanchego/actions/runs/19939802304/job/57174355677?pr=4578. 

The tests failed after about 2 minutes, which would indicate flakiness no?

File: graft/coreth/rpc/websocket_test.go (hunk 2 above)
Comment (JonathanOppenheimer) [reply graft/coreth/rpc/websocket_test.go:186]: Removed.

File: graft/subnet-evm/rpc/websocket_test.go (hunk 5 above)
Comment (JonathanOppenheimer) [reply graft/subnet-evm/rpc/websocket_test.go:272]: Wdym skipped for both? I do skip this test both in coreth and subnet-evm.

**Comment by JonathanOppenheimer** [comment]
> Also, did you confirm that running the tests in parallel is actually faster? Sometimes with race detection, running in parallel will be not-significant or even slower...

Yes, I did so. Here are the results for the of the core package: 

**Race detection**

| Branch | Time | Speedup |
|--------------|-----:|--------:|
| master | 132.49s | - |
| JonathanOppenheimer/skip-geth-flakes | 127.84s | 3.5% faster |

**No race detection**

| Branch | Time | Speedup |
|--------------|-----:|--------:|
| master | 77.61s | - |
| JonathanOppenheimer/skip-geth-flakes| 30.10s | 61% faster |

--- 

So pretty big results for local development, and appears to be a minor improvement for CI - the CI for coreth appeared to have run faster in CI, but it's pretty hard to compare with that as it's so variable.

File: graft/coreth/core/blockchain_repair_test.go [hunk 10]
```diff
@@ -474,8 +532,14 @@ func testLongReorgedShallowRepair(t *testing.T, snapshots bool) {
...
 // chains to be rolled back to the committed block, but the chain data itself left in the database
 // for replaying.
-func TestLongReorgedDeepRepair(t *testing.T)              { testLongReorgedDeepRepair(t, false) }
-func TestLongReorgedDeepRepairWithSnapshots(t *testing.T) { testLongReorgedDeepRepair(t, true) }
+func TestLongReorgedDeepRepair(t *testing.T) {
+	t.Parallel()
+	testLongReorgedDeepRepair(t, false)
+}
+func TestLongReorgedDeepRepairWithSnapshots(t *testing.T) {
+	t.Parallel()
```
Comment (alarso16) [inline graft/coreth/core/blockchain_repair_test.go]: Instead of putting `t.Parallel()` in each of these, you can put it in the lower calls that are shared. Then you only need to put it in like two places

File: graft/coreth/core/blockchain_test.go (hunk 1 above)
Comment (alarso16) [reply graft/coreth/core/blockchain_test.go:379]: Hmm this is suspicious, I digress

File: graft/evm/rpc/websocket_test.go [hunk 11]
```diff
@@ -269,6 +269,9 @@ func TestClientWebsocketPing(t *testing.T) {
 
 // This checks that the websocket transport can deal with large messages.
 func TestClientWebsocketLargeMessage(t *testing.T) {
+	t.Skip("Flaky test from go-ethereum")
+	t.Parallel()
```
Comment (alarso16) [inline graft/evm/rpc/websocket_test.go]: If it's flaky, it doesn't need to occur in parallel

**Comment by alarso16** [comment]
> > Also, did you confirm that running the tests in parallel is actually faster? Sometimes with race detection, running in parallel will be not-significant or even slower...
> 
> Yes, I did so.

I don't think 3% is sufficient. In local development, I assume many people just use `../evm/scripts/build_test.sh`

**Comment by JonathanOppenheimer** [comment]
> > > Also, did you confirm that running the tests in parallel is actually faster? Sometimes with race detection, running in parallel will be not-significant or even slower...
> > 
> > 
> > Yes, I did so.
> 
> I don't think 3% is sufficient. In local development, I assume many people just use `../evm/scripts/build_test.sh`

I use the IDE test runner fairly frequently, so this would be useful for me. I can also alternatively remove it entirely as you wish. Does anyone else have an opinion on this? @maru-ava?

File: graft/coreth/core/blockchain_repair_test.go (hunk 10 above)
Comment (JonathanOppenheimer) [reply graft/coreth/core/blockchain_repair_test.go]: Oh yup we can half the number of calls (24 -> 12). I actually didn't know it would work in the single function -- it's the same `t` so idk why I though that.

File: graft/coreth/core/blockchain_repair_test.go [hunk 12]
```diff
@@ -64,10 +64,15 @@ type rewindTest struct {
...
 // chain to be rolled back to the committed block, but the chain data itself left
 // in the database for replaying.
-func TestShortRepair(t *testing.T)              { testShortRepair(t, false) }
-func TestShortRepairWithSnapshots(t *testing.T) { testShortRepair(t, true) }
+func TestShortRepair(t *testing.T) {
+	testShortRepair(t, false)
+}
+func TestShortRepairWithSnapshots(t *testing.T) {
+	testShortRepair(t, true)
+}
```
Comment (ceyonur) [inline graft/coreth/core/blockchain_repair_test.go]: can we revert those whitespace/newline changes?

File: graft/coreth/core/blockchain_repair_test.go [hunk 13]
```diff
@@ -64,10 +64,15 @@ type rewindTest struct {
...
 
 func testShortRepair(t *testing.T, snapshots bool) {
+	t.Parallel()
```
Comment (ceyonur) [inline graft/coreth/core/blockchain_repair_test.go]: How much are we confident parallelizing tests in this package will resolve flaky tests? Probably none of these test were written to be parallel and I have a concern they will flake more with race tests.

Comment (JonathanOppenheimer) [reply graft/coreth/core/blockchain_repair_test.go]: Making the tests parallel has nothing to do with resolving flakes -- it's to speed the execution time of to not time out. See this whole comment thread: https://github.com/ava-labs/avalanchego/pull/4902#issuecomment-3792106445. 

If you don't think the speedup is worth, I will remove all of it

File: graft/coreth/core/blockchain_repair_test.go (hunk 12 above)
Comment (JonathanOppenheimer) [reply graft/coreth/core/blockchain_repair_test.go]: Yup!

File: graft/coreth/core/blockchain_repair_test.go (hunk 13 above)
Comment (alarso16) [reply graft/coreth/core/blockchain_repair_test.go]: I'm rather confident that the flakiness of the core package (except the offline pruning test, not sure about this one) is entirely due to testing timeouts. However, running in parallel with race detection seems to make no difference, so I am for removing most of these changes and simply increasing the timeout on the coreth and subnet-evm tests

Comment (JonathanOppenheimer) [reply graft/coreth/core/blockchain_repair_test.go]: Alright I will just remove them. I still do think the 60% speed up benefit locally is nice, but I guess CI takes priority.

File: graft/evm/scripts/build_test.sh (hunk 3 above)
Comment (alarso16) [reply graft/evm/scripts/build_test.sh]: I don't think that's true. We only are extending the deadline because of the `core` tests, which will NEVER be here

Comment (JonathanOppenheimer) [reply graft/evm/scripts/build_test.sh]: Ok reverted.
