### PR TITLE
Revert removal of legacy P-chain block parsing

### LINKED ISSUE #2865: Node not starting up with v1.11.3
**Describe the bug**
Was syncing a new node last night on AGo v11.2
Everything seemed to going well but I noticed things had stalled out with ~10 minutes left on the sync. I upgraded AGo to v11.3 this morning and the script is hanging as below - no logs in 2 hours

```
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.840] INFO <P Chain> snowman/transitive.go:97 initializing consensus engine
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.841] INFO health/worker.go:109 registered new check and initialized its state to failing {"namespace": "health", "name": "P", "tags": ["11111111111111111111111111111111LpoYY"]}
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.841] INFO server/server.go:211 adding route {"url": "/ext/bc/11111111111111111111111111111111LpoYY", "endpoint": ""}
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.841] INFO health/worker.go:109 registered new check and initialized its state to failing {"namespace": "readiness", "name": "bootstrapped", "tags": ["application"]}
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.841] INFO health/worker.go:109 registered new check and initialized its state to failing {"namespace": "health", "name": "bootstrapped", "tags": ["application"]}
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.841] INFO <P Chain> bootstrap/bootstrapper.go:159 starting bootstrapper
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.842] INFO chains/manager.go:1306 starting chain creator
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.842] INFO node/node.go:629 writing process context {"path": "/home/nodeuser/.avalanchego/process.json"}
Mar 23 02:50:19 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:19.842] INFO node/node.go:656 API server listening {"uri": "http://[::]:9650"}
Mar 23 02:50:25 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:25.986] INFO <P Chain> bootstrap/bootstrapper.go:390 starting to fetch blocks {"numAcceptedBlocks": 1, "numMissingBlocks": 2}
Mar 23 02:50:49 Ubuntu-2204-jammy-amd64-base avalanchego[499457]: [03-23|02:50:49.791] INFO health/worker.go:255 check started passing {"namespace": "health", "name": "network", "tags": ["application"]}
```

Curling gives
```
nodeuser@Ubuntu-2204-jammy-amd64-base:~/nodes/base$ curl -d '{"id":0,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false]}'   -H "Content-Type: application/json" http://localhost:9651
curl: (52) Empty reply from server
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Node syncing successfully

**Screenshots**

**Logs**
If applicable, please include the relevant logs that indicate a problem and/or the log directory of your node. By default, this can be found at `~/.avalanchego/logs/`.
See above

**Metrics**
If applicable, please include any metrics gathered from your node to assist us in diagnosing the problem.

**Operating System**
Ubuntu

**Additional context**

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../security/policy)**

### PR DESCRIPTION
**Pull request by StephenButtolph**
## Why this should be merged

Resolves #2865 

## How this works

Partially reverts #2825.

It seems there was a small bug in #1719 (see: https://github.com/ava-labs/avalanchego/pull/1719#discussion_r1536714191) that caused `PruneAndIndex` not to update the `{blkID -> blk + status}` mapping into `{blkID -> blk}` mapping as intended.

This means that some nodes still have the `{blkID -> blk + status}` mapping even though they have all finished the `pruning` process.

This PR adds back support for parsing this legacy index format. A followup PR will be needed to perform the index format update.

## How this was tested

- [x] Verified block fetching works on a long lived database
- [x] CI

### CODE REVIEW

**Review by dhrubabasu — APPROVED** [review]

File: vms/platformvm/state/state.go [hunk 1]
```diff
@@ -178,6 +179,12 @@ type State interface {
 	Close() error
 }
 
+// TODO: Remove after v1.12.x is activated
+type stateBlk struct {
```
Comment (patrick-ogrady) [inline vms/platformvm/state/state.go:183]: nit: can we add more detail about the history of this struct (i.e. legacy format that some long-lived dbs have)

**Review by patrick-ogrady — APPROVED** [review]

**Comment by PinkFromTheFuture** [comment]
I can confirm that this solves the issue, syncing like a champ, thank you!
