### PR TITLE
Defer parser initialization to Start

### LINKED ISSUE #1440: get panic while initializing (v1.10.0)
**Describe the bug**
I get a panic while starting up

```
[04-28|12:40:48.031] INFO <X Chain> avm/vm.go:275 address transaction indexing is disabled
[04-28|12:40:48.032] INFO chains/manager.go:757 creating proposervm wrapper {"activationTime": "[09-22|21:00:00.000]", "minPChainHeight": 793005, "minBlockDelay": "1s"}
[04-28|12:40:48.032] INFO <X Chain> snowman/transitive.go:89 initializing consensus engine
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xcba826]

goroutine 1949 [running]:
github.com/ava-labs/avalanchego/vms/proposervm.(*VM).getPostForkBlock(0xc0233a0d00, {0x1c08748, 0xc0000440c8}, {0x2a, 0xa9, 0x2c, 0x79, 0xb7, 0xb, 0x46, ...})
        /home/runner/work/avalanchego-internal/avalanchego-internal/vms/proposervm/vm.go:665 +0xa6
github.com/ava-labs/avalanchego/vms/proposervm.(*VM).parsePostForkBlock(0xc0233a0d00, {0x1c08748, 0xc0000440c8}, {0xc0156086c0?, 0x18?, 0xc001214c00?})
        /home/runner/work/avalanchego-internal/avalanchego-internal/vms/proposervm/vm.go:608 +0xb9
github.com/ava-labs/avalanchego/vms/proposervm.(*VM).ParseBlock(0xc0233a0d00, {0x1c08748, 0xc0000440c8}, {0xc0156086c0, 0x215, 0x240})
        /home/runner/work/avalanchego-internal/avalanchego-internal/vms/proposervm/vm.go:266 +0x45
github.com/ava-labs/avalanchego/vms/metervm.(*blockVM).ParseBlock(0xc005146fc0, {0x1c08748?, 0xc0000440c8?}, {0xc0156086c0?, 0x215?, 0x240?})
        /home/runner/work/avalanchego-internal/avalanchego-internal/vms/metervm/block_vm.go:112 +0xde
github.com/ava-labs/avalanchego/snow/engine/snowman/bootstrap.(*parser).Parse(0xc00f47e580, {0x1c08748?, 0xc0000440c8?}, {0xc0156086c0?, 0xc011b498cb?, 0x0?})
        /home/runner/work/avalanchego-internal/avalanchego-internal/snow/engine/snowman/bootstrap/block_job.go:33 +0x42
github.com/ava-labs/avalanchego/snow/engine/common/queue.(*state).GetJob(0xc016a5fa70, {0x1c08748, 0xc0000440c8}, {0x2a, 0xa9, 0x2c, 0x79, 0xb7, 0xb, 0x46, ...})
        /home/runner/work/avalanchego-internal/avalanchego-internal/snow/engine/common/queue/state.go:244 +0xf0
github.com/ava-labs/avalanchego/snow/engine/common/queue.(*JobsWithMissing).cleanRunnableStack(0xc016efd940, {0x1c08748, 0xc0000440c8})
        /home/runner/work/avalanchego-internal/avalanchego-internal/snow/engine/common/queue/jobs.go:402 +0x1e5
github.com/ava-labs/avalanchego/snow/engine/common/queue.(*JobsWithMissing).SetParser(...)
        /home/runner/work/avalanchego-internal/avalanchego-internal/snow/engine/common/queue/jobs.go:275
github.com/ava-labs/avalanchego/snow/engine/snowman/bootstrap.New({0x1c08748, 0xc0000440c8}, {{0xc013381ce0, {0x1c1c6d0, 0xc0004603f0}, 0x14, 0x1d448e93be9d1ec, {0x1c16520, 0xc00f447b00}, {0x1c22718, ...}, ...}, ...}, ...)
        /home/runner/work/avalanchego-internal/avalanchego-internal/snow/engine/snowman/bootstrap/bootstrapper.go:112 +0x5fd
github.com/ava-labs/avalanchego/chains.(*manager).createAvalancheChain(0xc0111a8380, 0xc013381ce0, {0xc01aaf80ed, 0x487ce, 0x49f13}, {0x1c1c6d0, 0xc0004603f0}, {0x1c1c6d0?, 0xc0004603f0?}, {0x7f4f885c3510, ...}, ...)
        /home/runner/work/avalanchego-internal/avalanchego-internal/chains/manager.go:888 +0x298a
github.com/ava-labs/avalanchego/chains.(*manager).buildChain(0xc0111a8380, {{0xed, 0x5f, 0x38, 0x34, 0x1e, 0x43, 0x6e, 0x5d, 0x46, ...}, ...}, ...)
        /home/runner/work/avalanchego-internal/avalanchego-internal/chains/manager.go:545 +0x10ea
github.com/ava-labs/avalanchego/chains.(*manager).createChain(0xc0111a8380, {{0xed, 0x5f, 0x38, 0x34, 0x1e, 0x43, 0x6e, 0x5d, 0x46, ...}, ...})
        /home/runner/work/avalanchego-internal/avalanchego-internal/chains/manager.go:335 +0x3d8
github.com/ava-labs/avalanchego/chains.(*manager).dispatchChainCreator(0xc0111a8380)
        /home/runner/work/avalanchego-internal/avalanchego-internal/chains/manager.go:1384 +0xc5
created by github.com/ava-labs/avalanchego/chains.(*manager).StartChainCreator
        /home/runner/work/avalanchego-internal/avalanchego-internal/chains/manager.go:1363 +0x390
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
no error
**Screenshots**

**Logs**
If applicable, please include the relevant logs that indicate a problem and/or the log directory of your node. By default, this can be found at `~/.avalanchego/logs/`.

**Metrics**
If applicable, please include any metrics gathered from your node to assist us in diagnosing the problem.

**Operating System**
Which OS you used to reveal the bug.
ubuntu20.0.4
**Additional context**

https://github.com/ava-labs/avalanchego/tree/v1.10.0

**To best protect the Avalanche community security bugs should be reported in accordance to our [Security Policy](../security/policy)**

### PR DESCRIPTION
**Pull request by StephenButtolph**
## Why this should be merged

Resolves #1440

## How this works

On the X-chain, the Snowman VM is not guaranteed to be `Initialized` until `Start` is called on the bootstrapper engine. When initializing the job parser it is possible to call `ParseBlock`, so initializing the job parser must be deferred until `Start` has been called.

## How this was tested

TODO

### CODE REVIEW

**Review by joshua-kim — APPROVED** [review]

File: snow/engine/snowman/bootstrap/block_job.go [hunk 1]
```diff
@@ -45,7 +44,6 @@ func (p *parser) Parse(ctx context.Context, blkBytes []byte) (queue.Job, error)
 }
 
 type blockJob struct {
-	parser                  *parser
```
Comment (StephenButtolph) [inline snow/engine/snowman/bootstrap/block_job.go:48]: This isn't really part of this PR... but this was dead code and having it here made the test harder to make... win win removing it

File: snow/engine/snowman/bootstrap/bootstrapper_test.go [hunk 2]
```diff
@@ -1510,3 +1502,127 @@ func TestBootstrapContinueAfterHalt(t *testing.T) {
...
+		BootstrappedF: func(ids.ID) {
+			isBootstrapped = true
+		},
+	}
+
+	sender.CantSendGetAcceptedFrontier = false
+
+	peer := ids.GenerateTestNodeID()
+	if err := peers.Add(peer, nil, ids.Empty, 1); err != nil {
+		t.Fatal(err)
```
Comment (hexfusion) [inline snow/engine/snowman/bootstrap/bootstrapper_test.go:1537]: any reason to not use `require.NoError` here?

**Review by hexfusion — APPROVED** [review]

File: snow/engine/snowman/bootstrap/bootstrapper_test.go (hunk 2 above)
Comment (StephenButtolph) [reply snow/engine/snowman/bootstrap/bootstrapper_test.go:1537]: CTRL+C -> CTRL+V was the reason

File: snow/engine/snowman/bootstrap/bootstrapper_test.go [hunk 3]
```diff
@@ -1510,3 +1502,127 @@ func TestBootstrapContinueAfterHalt(t *testing.T) {
...
+		StartupTracker:                 startupTracker,
+		Sender:                         sender,
+		BootstrapTracker:               bootstrapTracker,
+		Timer:                          &common.TimerTest{},
+		AncestorsMaxContainersSent:     2000,
+		AncestorsMaxContainersReceived: 2000,
+		SharedCfg:                      &common.SharedConfig{},
+	}
+
+	snowGetHandler, err := getter.New(vm, commonConfig)
```
Comment (gyuho) [inline snow/engine/snowman/bootstrap/bootstrapper_test.go:1556]:
```suggestion
	snowGetHandler, err := getter.New(vm, commonConfig)
	require.NoError(err)
```

File: snow/engine/snowman/bootstrap/bootstrapper_test.go (hunk 2 above)
Comment (StephenButtolph) [reply snow/engine/snowman/bootstrap/bootstrapper_test.go]: addressed

File: snow/engine/snowman/bootstrap/bootstrapper_test.go (hunk 3 above)
Comment (gyuho) [reply snow/engine/snowman/bootstrap/bootstrapper_test.go:1556]: Ah you beated me to it

Comment (StephenButtolph) [reply snow/engine/snowman/bootstrap/bootstrapper_test.go:1556]: Switched to use `require` everywhere in this test.

**Review by gyuho — APPROVED** [review]
