### PR TITLE
fix(sync): resolve shutdown deadlock in code queue during Firewood state sync

### LINKED ISSUE #5129: State sync shutdown deadlock when syncing with Firewood
## Problem

When state syncing with Firewood, sending SIGINT (Ctrl+C) causes the node to hang indefinitely during shutdown. The `ChainRouter.Shutdown` times out because the C-Chain handler's `asyncMessagePool.Wait()` never returns.

### Reproducibility steps
1. Start node
2. Commit genesis block
3. Start state syncing (Firewood)
4. Hit Ctrl+C
5. Node hangs for 14+ minutes, then logs `timed out while shutting down`

### Root cause

A circular deadlock between three components that share the handler's bounded async message pool:

1. Code syncer workers block in `GetCode` -> `WaitForResult`, waiting for AppResponse messages to be delivered by the handler pool
2. Handler pool goroutines are stuck processing range proof AppResponse callbacks, which call `CommitRangeProof` -> `AddCode`, blocking on a full code queue channel (capacity 5000)
3. The code queue channel is full because the code syncer workers can't drain it (they're waiting for GetCode responses that need the handler pool)

After careful analysis we discovered tha `Shutdown` doesn't break this cycle because:
- The code queue's `quit` channel was wired to `StateSyncDone`, which only closes after the sync goroutine finishes, but the sync goroutine can't finish because of the deadlock (circular dependency)
- The sync context cancellation doesn't reach `AddCode` because it runs in the handler's async pool, not in the sync errgroup

### PR DESCRIPTION
**Pull request by powerslider**
## Why this should be merged

Check #5129 

## How this works

- `AddCode` blocked the handler's async message pool goroutine when the channel was full, preventing `GetCode` responses from being delivered and creating a circular deadlock.
- Redesign the code queue as a fan-in/fan-out bridge with a single sender goroutine. `AddCode` appends hashes to a mutex-protected internal queue and signals the sender via a non-blocking channel send, so it never blocks the caller. The sender drains pending hashes to the output channel, and is cancelled on `Shutdown` or drained on `Finalize`.
- Wire `client.Shutdown` to call `codeQueue.Shutdown`, replacing the `StateSyncDone` quit channel that created a circular dependency.

## How this was tested

new UT into code queue tests

## Need to be documented in RELEASES.md?

no

resolves #5129

Signed-off-by: Tsvetan Dimitrov (tsvetan.dimitrov@avalabs.org)

### CODE REVIEW

File: graft/evm/sync/code/queue.go [hunk 1]
```diff
@@ -148,40 +124,69 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
-			return ErrFailedToAddCodeHashesToQueue
-		case <-ctx.Done():
-			return ctx.Err()
+	// Spawn a goroutine to push to the channel.
+	// The goroutine may block on channel send but does NOT block the caller.
+	q.eg.Go(func() error {
+		for _, h := range codeHashes {
+			select {
+			case q.ch <- h:
+			case <-q.done:
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go]: Why not just wait on the context? I know it's bad practice to put a context in a struct (not totally clear why), but I also don't know how this is any different

File: graft/evm/sync/code/queue.go [hunk 2]
```diff
@@ -24,26 +25,28 @@ var (
...
-	// `in` and `out` MUST be the same channel. We need to be able to set `in`
-	// to nil after closing, to avoid a send-after-close, but
-	// [CodeQueue.CodeHashes] MUST NOT return a nil channel otherwise consumers
-	// will block permanently.
-	in            chan<- common.Hash // Invariant: open or nil, but never closed
-	out           <-chan common.Hash // Invariant: never nil
-	chanLock      sync.RWMutex
-	closeChanOnce sync.Once // See usage in [CodeQueue.closeOutChannelOnce]
+	db ethdb.Database
+	ch chan common.Hash
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go]: `ch` is a bad name when there's a lot of channels floating around IMO

File: graft/evm/sync/engine/client.go [hunk 3]
```diff
@@ -286,6 +287,9 @@ func (c *client) Shutdown() error {
 	if c.cancel != nil {
 		c.cancel()
 	}
+	if c.codeQueue != nil {
+		c.codeQueue.Shutdown()
+	}
```
Comment (alarso16) [inline graft/evm/sync/engine/client.go:292]: Don't we NEED to flush pending code to disk for next startup? Otherwise, we won't be able to restart a state sync

File: graft/evm/sync/code/queue.go (hunk 1 above)
Comment (powerslider) [reply graft/evm/sync/code/queue.go]: ok, this is a bit of a can of worms, but I'll do my best to describe facts, best practices and our specific usage here. First of all you are completely right on this observation and I don't argue with that at all.

The "don't store context in structs" guidance from the [Go blog](https://go.dev/blog/context-and-structs) and [this article](https://zenhorace.dev/blog/context-control-go/) is about request-scoped contexts being stored and reused across calls with different lifetimes. The classic example from the Go blog:

> "The caller's lifetime is intermingled with a shared context, and the context is scoped to the lifetime where the Worker is created."

That's not what we're doing here. We have two separate concerns:

- `ctx` (function parameter on `AddCode`): per-call cancellation from the caller, honored in the `select`
- `q.done` / stored context (struct field): Queue lifetime signal for internal goroutine cancellation

The stored context controls the struct's own background goroutines, not caller requests. It's functionally identical to storing a `quit chan struct{}` (which is what the old code did). Neither article addresses this use case as an anti-pattern.

That said, I prefer `done <-chan struct{}` over storing the context directly because:
- It narrows the surface area. A `context.Context` carries values, deadlines, and cancellation. We only need the cancellation signal. Storing `done` makes it clear the struct can only listen for cancellation, not extract values or deadlines from it.
- It makes misuse harder. With a stored context, someone in the future might pass `q.ctx` to a function call, accidentally tying that call's lifetime to the queue's internal context. With `done`, the only thing you can do is `select` on it.
- It matches the existing codebase pattern. The old code used `quit <-chan struct{}` for the same purpose.

File: graft/evm/sync/engine/client.go (hunk 3 above)
Comment (powerslider) [reply graft/evm/sync/engine/client.go:292]: Disk markers are safe here. `AddCode` persists the to-fetch markers to disk before spawning the background goroutine (the `batch.Write()` happens synchronously). When `Shutdown` cancels the `errgroup` context, goroutines that were mid-send bail out, but their hashes are already on disk. On restart, `init()` calls `recoverUnfetchedCodeHashes` which picks them up.

Added a comment on `Shutdown` to make this explicit.

File: graft/evm/sync/code/queue.go [hunk 4]
```diff
@@ -148,40 +124,69 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+		for _, h := range codeHashes {
+			select {
+			case q.ch <- h:
+			case <-q.done:
+				return nil // cancelled - hashes remain as disk markers
+			}
 		}
-	}
+		return nil
+	})
```
[the remark this answers is not in the document]
Comment (powerslider) [reply graft/evm/sync/code/queue.go]: Each `AddCode` spawns one goroutine that may block on channel send. In practice the accumulation is bounded by production rate (the network round-trip time for range proof/leaf responses), and the number of producers is small (8 leaf workers for `hashdb`, or handler pool size for Firewood). If this becomes a concern we can add `eg.SetLimit(N)`, though that reintroduces backpressure which is what caused the original deadlock. 

We can keep an eye on this for the future, but for now I wouldn't change anything.

File: graft/evm/sync/code/queue.go [hunk 5]
```diff
@@ -148,40 +126,77 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
-	for _, h := range codeHashes {
-		select {
-		case q.in <- h: // guaranteed to be open or nil, but never closed
-		case <-q.quit:
-			return ErrFailedToAddCodeHashesToQueue
-		case <-ctx.Done():
-			return ctx.Err()
+	// Defensive copy: the goroutine outlives the caller and must not share
+	// the backing array.
+	hashesCopy := append([]common.Hash(nil), codeHashes...)
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go]: Why not use `slices.Clone`? I'm kind of surprised we don't have a linter to catch this

File: graft/evm/sync/code/queue.go [hunk 6]
```diff
@@ -60,84 +62,60 @@ func WithCapacity(n int) QueueOption {
...
 
-	// Mark this enqueue as in-flight immediately so shutdown paths wait for us
-	// before closing the output channel.
-	q.chanLock.RLock()
-	defer q.chanLock.RUnlock()
-	if q.in == nil {
-		// Although this will happen anyway once the `select` is reached,
-		// bailing early avoids unnecessary database writes.
-		return ErrFailedToAddCodeHashesToQueue
+	if err := ctx.Err(); err != nil {
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go:105]: Why did you decide to add this?

File: graft/evm/sync/code/queue.go [hunk 7]
```diff
@@ -148,40 +126,77 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+// markClosed prevents new AddCode goroutines. Must precede eg.Wait.
+func (q *Queue) markClosed() {
+	q.closeMu.Lock()
+	defer q.closeMu.Unlock()
+	q.closed = true
+}
+
+// stop drains in-flight goroutines and closes the channel.
+// If cancelCtx is true, stuck goroutines are unblocked first.
+func (q *Queue) stop(cancelCtx bool) {
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go]: The name of the `bool` confused me - I expected it to be a context. If you agree, would you change the name?

File: graft/evm/sync/code/queue.go [hunk 8]
```diff
@@ -148,40 +126,77 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+	q.markClosed()
+	if cancelCtx {
+		q.cancel()
+	}
+	// The errgroup goroutines spawned by AddCode never return errors,
+	// so it is safe to drop the error here.
+	_ = q.eg.Wait()
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go]: Weird to me that there isn't a waitgroup with a context

File: graft/evm/sync/code/queue_test.go [hunk 9]
```diff
@@ -89,157 +86,140 @@ func TestCodeQueue(t *testing.T) {
...
 	}
 }
 
-// Test that Finalize waits for in-flight AddCode calls to complete before closing the channel.
-func TestCodeQueue_FinalizeWaitsForInflightAddCodeCalls(t *testing.T) {
-	const capacity = 1
+// TestFinalizeFlushesAllHashes verifies that AddCode is non-blocking and
+// Finalize waits for all background sends to complete.
+func TestFinalizeFlushesAllHashes(t *testing.T) {
+	defer goleak.VerifyNone(t, goleak.IgnoreCurrent())
```
Comment (alarso16) [inline graft/evm/sync/code/queue_test.go]: Can you put goleak in the TestMain? If not, that seems like a bug

File: graft/evm/sync/code/queue_test.go [hunk 10]
```diff
@@ -248,3 +228,71 @@ func TestQuitAndAddCodeRace(t *testing.T) {
 		})
 	}
 }
+
+// TestConcurrentAddCodeAndConsume stress-tests concurrent producers and a
+// single consumer on a small-capacity channel.
+func TestConcurrentAddCodeAndConsume(t *testing.T) {
```
Comment (alarso16) [inline graft/evm/sync/code/queue_test.go:233]: This test doesn't really make sense to me. I don't think it tests anything you aren't already testing - the others are pretty thorough

File: graft/evm/sync/code/queue_test.go [hunk 11]
```diff
@@ -248,3 +228,71 @@ func TestQuitAndAddCodeRace(t *testing.T) {
...
+		capacity          = 2
+	)
+	db := rawdb.NewMemoryDatabase()
+	q, err := NewQueue(db, WithCapacity(capacity))
+	require.NoError(t, err)
+
+	// AddCode is non-blocking, but we want concurrent calls for stress.
+	var producerWg sync.WaitGroup
+	producerErrs := make([]error, numProducers)
+	producerWg.Add(numProducers)
```
Comment (alarso16) [inline graft/evm/sync/code/queue_test.go]: I think you should use an errgroup, since it doesn't matter which one errors. Also as a side note, waitgroups now also have a `Go` method

File: graft/evm/sync/code/queue.go (hunk 6 above)
Comment (powerslider) [reply graft/evm/sync/code/queue.go:105]: Without it, we'd do a full DB batch write (persisting markers) and spawn a background goroutine, only for the goroutine's `select` to immediately hit `<-ctx.Done()` and bail. The early check short-circuits that.

File: graft/evm/sync/code/queue_test.go (hunk 10 above)
Comment (powerslider) [reply graft/evm/sync/code/queue_test.go:233]: I'd like to keep this one. It's the only test that exercises multiple concurrent producers calling `AddCode` simultaneously with a real consumer and verifies **correctness** (all `numProducers * hashesPerProducer` hashes received). `TestShutdownAndAddCodeRace` only checks for panics/leaks under concurrency, not that all hashes actually arrive. This test covers the production pattern where multiple leaf workers call `AddCode` concurrently. That said, I refactored it to use `errgroup` as you suggested.

File: graft/evm/sync/code/queue.go [hunk 12]
```diff
@@ -171,10 +172,10 @@ func (q *Queue) markClosed() {
 }
 
 // stop drains in-flight goroutines and closes the channel.
-// If cancelCtx is true, stuck goroutines are unblocked first.
-func (q *Queue) stop(cancelCtx bool) {
+// If cancel is true, stuck goroutines are unblocked first.
+func (q *Queue) stop(cancel bool) {
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go]: `shouldCancel? or something similar?

File: graft/evm/sync/code/queue.go [hunk 13]
```diff
@@ -148,40 +127,77 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
-			return ErrFailedToAddCodeHashesToQueue
-		case <-ctx.Done():
-			return ctx.Err()
+	// Defensive copy: the goroutine outlives the caller and must not share
+	// the backing array.
+	hashesCopy := slices.Clone(codeHashes)
+
+	// Spawn a goroutine to push to the channel.
+	// The goroutine may block on channel send but does NOT block the caller.
+	q.eg.Go(func() error {
```
Comment (ceyonur) [inline graft/evm/sync/code/queue.go]: Seems `AddCode` has changed in a subtle but important way.

With the new flow, this can return nil before any enqueue is guaranteed to have happened. After that, caller ctx cancellation is handled inside the goroutine (`case <-ctx.Done(): return nil`), so `AddCode` can report success even if none of the hashes ever make it to `hashCh`. While this seems the actual fix for the deadlock, I wonder if it's aligned with callers' assumptions.

Comment (ceyonur) [inline graft/evm/sync/code/queue.go]: Also is it ok to spawn a new goroutine everytime? Should we consider a bounded worker pool etc?

Comment (powerslider) [reply graft/evm/sync/code/queue.go]: I answered this here https://github.com/ava-labs/avalanchego/pull/5130#discussion_r2988814588, but am open to do something like a worker pool if you think we should do this now.

Comment (powerslider) [reply graft/evm/sync/code/queue.go]: Yes, `AddCode` can return nil before hashes reach `hashCh` since that's the intentional design change that breaks the deadlock. The durability guarantee comes from the disk markers written synchronously before the goroutine spawns. If the caller's context cancels, the goroutine bails, but the hashes remain as on-disk markers. On restart, `init()` recovers them via `recoverUnfetchedCodeHashes`. So the contract is - a nil return means the hashes "will eventually be fetched (possibly after restart)", not that they're already on `hashCh`. If ctx cancels, sync is shutting down anyway and no consumer would be reading from `hashCh` at that point.

Comment (ceyonur) [reply graft/evm/sync/code/queue.go]: I think we should either resolve this here or an immediate follow-up PR. Leaving this unbounded sound scary given that this can be playable with respect to leaf responses and I suspect an adversary can spawn many goroutines with valid but small leaf responses?

Comment (powerslider) [reply graft/evm/sync/code/queue.go]: ok, I re-designed the approach to use a fan-in/fan-out pattern to totally eliminate the goroutine per `AddCode` call https://github.com/ava-labs/avalanchego/pull/5130/changes/68c3fe0d0f9c857aef6af7811f775e9a3e449bbd

File: graft/evm/sync/code/queue.go [hunk 14]
```diff
@@ -148,40 +127,113 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+	if shouldCancel {
+		q.cancel()
+	}
+	q.closeInOnce.Do(func() {
+		close(q.in)
+	})
+	<-q.senderDone
+}
+
+// sender forwards hashes from pending to out. It owns out and closes it on exit.
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go]:
```suggestion
// sender forwards hashes from pending to out. It owns `q.out` and closes it on exit.
```
This looked like a typo at first (or maybe I'm just getting tired)

File: graft/evm/sync/code/queue.go [hunk 15]
```diff
@@ -148,40 +127,113 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
-		case <-ctx.Done():
-			return ctx.Err()
-		}
+	q.pendingMu.Lock()
+	q.pending = append(q.pending, codeHashes...)
+	q.pendingMu.Unlock()
+
+	select {
+	case q.in <- struct{}{}:
+	default:
```
Comment (alarso16) [inline graft/evm/sync/code/queue.go:136]: Is this a common enough pattern you don't need to explain why it is safe to skip if you're blocked? It was relatively clear from reviewing the code, but might be tricky for future reviewers

File: graft/evm/sync/code/queue.go [hunk 16]
```diff
@@ -148,40 +127,113 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+
+func (q *Queue) markClosed() {
+	q.closeMu.Lock()
+	defer q.closeMu.Unlock()
+	q.closed = true
+}
+
+// stop waits for in-flight AddCode calls (via write lock), optionally cancels
+// the sender, signals no more work, and waits for the sender to exit.
+func (q *Queue) stop(shouldCancel bool) {
```
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go:164]: I'm a little confused by the comment? Does it actually wait for a write lock?

Comment (JonathanOppenheimer) [reply graft/evm/sync/code/queue.go:164]: Ah it's markclosed that waits for the lock

File: graft/evm/sync/code/queue.go [hunk 17]
```diff
@@ -148,40 +127,113 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+	q.markClosed()
+	if shouldCancel {
+		q.cancel()
+	}
+	q.closeInOnce.Do(func() {
+		close(q.in)
+	})
+	<-q.senderDone
```
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go]: shouldn't we also `q.cancel()` here?

File: graft/evm/sync/code/queue.go [hunk 18]
```diff
@@ -23,34 +23,36 @@ const defaultQueueCapacity = 5000
...
+	ErrQueueClosed = errors.New("code queue is closed")
 )
 
-// Queue implements the producer side of code fetching.
-// It accepts code hashes, persists durable "to-fetch" markers (idempotent per hash),
-// and enqueues the hashes as-is onto an internal channel consumed by the code syncer.
-// The queue does not perform in-memory deduplication or local-code checks - that is
-// the responsibility of the consumer.
+// Queue is a fan-in/fan-out bridge between code hash producers (leaf sync workers)
+// and the code syncer consumer. Producers call [AddCode] which persists durable
```
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go]: AddCode isn't linked properly

File: graft/evm/sync/code/queue.go [hunk 19]
```diff
@@ -59,85 +61,62 @@ func WithCapacity(n int) QueueOption {
 	})
 }
 
-// NewQueue creates a new code queue applying optional functional options.
-// The `quit` channel, if non-nil, MUST eventually be closed to avoid leaking a
-// goroutine.
-func NewQueue(db ethdb.Database, quit <-chan struct{}, opts ...QueueOption) (*Queue, error) {
-	// Create with defaults, then apply options.
+// NewQueue creates a code queue. Call [Finalize] for normal completion
+// or [Shutdown] for cancellation. Both are safe to call in any order.
```
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go]: Also not linked properly for a godoc.

File: graft/evm/sync/code/queue.go [hunk 20]
```diff
@@ -59,85 +61,62 @@ func WithCapacity(n int) QueueOption {
...
-	})
-	return done
-}
-
-// AddCode persists and enqueues new code hashes.
-// Persists idempotent "to-fetch" markers for all inputs and enqueues them as-is.
-// Returns errAddCodeAfterFinalize after a clean finalize and errFailedToAddCodeHashesToQueue on early quit.
+// AddCode persists code hashes as durable disk markers and enqueues them
+// for the sender goroutine. Never blocks the caller.
+// Returns [ErrQueueClosed] after [Shutdown] or [Finalize].
```
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go]: shutdown and finalize also not linked properly

File: graft/evm/sync/code/queue.go [hunk 21]
```diff
@@ -148,40 +127,113 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
-	if !q.closeChannelOnce() {
-		return errFailedToFinalizeCodeQueue
-	}
+	q.stop(false)
 	return nil
 }
 
+// Shutdown cancels the sender, waits for exit, then closes out.
+// Unsent hashes are safe as disk markers and will be recovered on restart.
+// Idempotent with [Finalize].
```
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go]: same here

File: graft/evm/sync/code/queue.go [hunk 22]
```diff
@@ -148,40 +127,113 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+
 	return nil
 }
 
-// Finalize signals that no further code hashes will be added.
-// Waits for in-flight enqueues to complete, then closes the output channel.
-// If the queue was already closed due to early quit, returns errFailedToFinalizeCodeQueue.
+// Finalize waits for all pending hashes to be sent, then closes out.
+// Idempotent with [Shutdown].
 func (q *Queue) Finalize() error {
```
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go:144]: What happens here if the code syncer has already been cancelled? Is `Finalize()` still safe if nothing is consuming `q.out` anymore?

File: graft/evm/sync/code/queue.go (hunk 15 above)
Comment (JonathanOppenheimer) [inline graft/evm/sync/code/queue.go:136]: Should we still be bounding queue growth here? It looks like while `pending` can keep growing forever if `AddCode()` is called faster than the consumer.

File: graft/evm/sync/code/queue.go (hunk 17 above)
Comment (powerslider) [reply graft/evm/sync/code/queue.go]: No because during `Finalize` we intentionally don't cancel so the sender can drain all pending hashes. During Shutdown, `stop(true)` already calls `q.cancel()` before signaling the sender, so the sender doesn't need to cancel redundantly.

File: graft/evm/sync/code/queue.go (hunk 15 above)
Comment (powerslider) [reply graft/evm/sync/code/queue.go:136]: Added a comment to clarify.

Comment (powerslider) [reply graft/evm/sync/code/queue.go:136]: `pending` growth is bounded in practice by production rate (8 leaf workers gated by network round-trips) and finite state size. Adding explicit bounds requires backpressure on `AddCode`, which risks reintroducing the deadlock this PR fixes. The memory footprint is just 32 bytes per hash in a flat slice vs 2-8KB stack per goroutine in the former approach.

File: graft/evm/sync/code/queue.go (hunk 22 above)
Comment (powerslider) [reply graft/evm/sync/code/queue.go:144]: `Finalize` blocks until all hashes are consumed, so it requires an active consumer. If the consumer has stopped, use `Shutdown` instead since it cancels the sender via context. If both are called concurrently, `Shutdown` rescues a stuck `Finalize`. I've clarified in the `Finalize` doc.

File: graft/evm/sync/code/queue.go [hunk 23]
```diff
@@ -148,40 +127,114 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+		q.cancel()
+	}
+	q.closeInOnce.Do(func() {
+		close(q.in)
+	})
+	<-q.senderDone
+}
+
+// sender forwards hashes from pending to out. It owns `q.out` and closes it on exit.
+func (q *Queue) sender() {
```
Comment (ceyonur) [inline graft/evm/sync/code/queue.go]: nit: maybe rename this to `forward` etc? `sender` sounds like it returns the sender

File: graft/evm/sync/code/queue.go [hunk 24]
```diff
@@ -59,85 +61,62 @@ func WithCapacity(n int) QueueOption {
...
+	ctx, cancel := context.WithCancel(context.Background())
+	q.cancel = cancel
+	q.done = ctx.Done()
+
+	go q.sender()
 
-	// Always initialize eagerly.
 	if err := q.init(); err != nil {
+		cancel()
+		<-q.senderDone
```
Comment (ceyonur) [inline graft/evm/sync/code/queue.go]: if we rename `sender` to `forward` I think this will sound better `forwardDone`

File: graft/evm/sync/code/queue.go [hunk 25]
```diff
@@ -148,40 +127,114 @@ func (q *Queue) AddCode(ctx context.Context, codeHashes []common.Hash) error {
...
+	for {
+		select {
+		case _, ok := <-q.in:
+			if !ok {
+				q.drainPending()
+				return
+			}
+			if q.drainPending() {
+				return
+			}
```
Comment (ceyonur) [inline graft/evm/sync/code/queue.go]: maybe something like
```
    stop := q.drainPending()
    if !ok || stop {
        return
    }
```

File: graft/evm/sync/code/queue.go [hunk 26]
```diff
@@ -23,34 +23,36 @@ const defaultQueueCapacity = 5000
...
+	done       <-chan struct{} // cancelled on Shutdown
+	senderDone chan struct{}   // closed when sender exits
+
+	closeMu     sync.RWMutex
+	closeInOnce sync.Once
+	closed      bool
+
+	pendingMu sync.Mutex
+	pending   []common.Hash
+	in        chan struct{} // producer signal, buffered to 1
```
Comment (ceyonur) [inline graft/evm/sync/code/queue.go:49]: I'd very like to reduce the complexity here but I'm not quite sure how. Maybe a `sync.Cond` can replace `in` + `closeInOnce` but still most of the complexity will stay. (unless we can make the `AddCode` blocking)

Comment (powerslider) [reply graft/evm/sync/code/queue.go:49]: `sync.Cond` can't be used in a `select` statement, which means we'd lose the ability to multiplex the producer wake up signal with context cancellation (`<-q.done`). 

The current design maps directly to the fan-in/fan-out pattern:
-  Fan-in: multiple producers append to `pending` under a mutex, then merge wake-ups via a buffered channel of size 1 (`in`).
- Fan-out: a single `forward()` goroutine drains `pending` and sends to `out`.
- Closing `in` signals "no more work" (`Finalize`), cancelling the context signals "stop now" (`Shutdown`).

I think this is simple enough since the `in` channel + `closeInOnce` is the minimal Go idiom for this giving us signal merging, clean shutdown via `close`, and `select` composability in three lines.

File: graft/evm/sync/code/queue.go (hunk 17 above)
Comment (JonathanOppenheimer) [reply graft/evm/sync/code/queue.go]: Got it

File: graft/evm/sync/code/queue.go [hunk 27]
```diff
@@ -59,85 +61,62 @@ func WithCapacity(n int) QueueOption {
...
-		// is desirable.
-		q.in = nil
-		done = true
-	})
-	return done
-}
-
-// AddCode persists and enqueues new code hashes.
-// Persists idempotent "to-fetch" markers for all inputs and enqueues them as-is.
-// Returns errAddCodeAfterFinalize after a clean finalize and errFailedToAddCodeHashesToQueue on early quit.
```
Comment (ceyonur) [inline graft/evm/sync/code/queue.go:119]: why have we removed comments?

File: graft/evm/sync/code/queue.go [hunk 28]
```diff
@@ -23,34 +23,36 @@ const defaultQueueCapacity = 5000
...
+	pendingMu sync.Mutex
+	pending   []common.Hash
+	in        chan struct{} // producer signal, buffered to 1
 
 	capacity int
 }
 
 type QueueOption = options.Option[Queue]
 
-// WithCapacity overrides the queue buffer capacity.
```
Comment (ceyonur) [inline graft/evm/sync/code/queue.go:53]: can we keep the comment?

File: graft/evm/sync/code/queue.go (hunk 27 above)
Comment (powerslider) [reply graft/evm/sync/code/queue.go:119]: it has been changed to:
```
// AddCode persists code hashes as durable disk markers and enqueues them
// for the forwarder goroutine. Never blocks the caller.
// Returns [ErrQueueClosed] after [Queue.Shutdown] or [Queue.Finalize].
```
Check the diff again.
